#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Sep 12, 2019 11:19:22 AM +1000  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m73" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 886x320+376+593
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 5764 1073
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Site Search"
    vTcl:DefineAlias "$top" "search_window" vTcl:Toplevel:WidgetProc "" 1
    checkbutton $top.che43 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Get Map} -variable che43 
    vTcl:DefineAlias "$top.che43" "get_map_chk" vTcl:WidgetProc "search_window" 1
    ttk::combobox $top.tCo51 \
        -font TkTextFont -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo51" "street_type_entry" vTcl:WidgetProc "search_window" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Unit No. :} 
    vTcl:DefineAlias "$top.lab53" "unit_label" vTcl:WidgetProc "search_window" 1
    entry $top.ent54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent54" "lot_entry" vTcl:WidgetProc "search_window" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {House No. :} 
    vTcl:DefineAlias "$top.lab55" "house_label" vTcl:WidgetProc "search_window" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Lot No. :} 
    vTcl:DefineAlias "$top.lab56" "lot_label" vTcl:WidgetProc "search_window" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Enter Site Info:} 
    vTcl:DefineAlias "$top.lab57" "saerch_header" vTcl:WidgetProc "search_window" 1
    entry $top.ent58 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent58" "house_entry" vTcl:WidgetProc "search_window" 1
    entry $top.ent62 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent62" "unit_entry" vTcl:WidgetProc "search_window" 1
    entry $top.ent63 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent63" "street_name_entry" vTcl:WidgetProc "search_window" 1
    entry $top.ent64 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent64" "postcode_entry" vTcl:WidgetProc "search_window" 1
    entry $top.ent65 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent65" "suburb_entry" vTcl:WidgetProc "search_window" 1
    label $top.lab66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Street Name:} 
    vTcl:DefineAlias "$top.lab66" "street_name_label" vTcl:WidgetProc "search_window" 1
    label $top.lab67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Suburb: 
    vTcl:DefineAlias "$top.lab67" "suburb_label" vTcl:WidgetProc "search_window" 1
    label $top.lab68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Postcode: 
    vTcl:DefineAlias "$top.lab68" "postcode_label" vTcl:WidgetProc "search_window" 1
    label $top.lab69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Street Type:} 
    vTcl:DefineAlias "$top.lab69" "street_type_label" vTcl:WidgetProc "search_window" 1
    button $top.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Search 
    vTcl:DefineAlias "$top.but71" "search_button" vTcl:WidgetProc "search_window" 1
    set site_3_0 $top.m73
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr43 \
        -background $vTcl(actual_gui_bg) -height 245 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 381 
    vTcl:DefineAlias "$top.scr43" "results_list_box" vTcl:WidgetProc "search_window" 1

    $top.scr43.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    text $top.tex45 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 104 -wrap word 
    .top42.tex45 configure -font "TkTextFont"
    .top42.tex45 insert end text
    vTcl:DefineAlias "$top.tex45" "address_textbox" vTcl:WidgetProc "search_window" 1
    text $top.tex46 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 104 -wrap word 
    .top42.tex46 configure -font "TkTextFont"
    .top42.tex46 insert end text
    vTcl:DefineAlias "$top.tex46" "suburb_textbox" vTcl:WidgetProc "search_window" 1
    label $top.lab49 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Address :} 
    vTcl:DefineAlias "$top.lab49" "r_address_label" vTcl:WidgetProc "search_window" 1
    label $top.lab50 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text {Suburb :} 
    vTcl:DefineAlias "$top.lab50" "r_suburb_label" vTcl:WidgetProc "search_window" 1
    button $top.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Copy 
    vTcl:DefineAlias "$top.but52" "copy_address_btn" vTcl:WidgetProc "search_window" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Copy 
    vTcl:DefineAlias "$top.but53" "copy_sub_btn" vTcl:WidgetProc "search_window" 1
    label $top.lab54 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {List of Search Results:} 
    vTcl:DefineAlias "$top.lab54" "search_results_label" vTcl:WidgetProc "search_window" 1
    label $top.lab58 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Returned Site Info:} 
    vTcl:DefineAlias "$top.lab58" "r_site_header_label" vTcl:WidgetProc "search_window" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Postcode :} 
    vTcl:DefineAlias "$top.lab59" "r_postcode_label" vTcl:WidgetProc "search_window" 1
    text $top.tex60 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 104 -wrap word 
    .top42.tex60 configure -font "TkTextFont"
    .top42.tex60 insert end text
    vTcl:DefineAlias "$top.tex60" "postcode_textbox" vTcl:WidgetProc "search_window" 1
    button $top.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Copy 
    vTcl:DefineAlias "$top.but61" "copy_postcode_btn" vTcl:WidgetProc "search_window" 1
    label $top.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Sitename :} 
    vTcl:DefineAlias "$top.lab62" "r_sitename_label" vTcl:WidgetProc "search_window" 1
    text $top.tex63 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 104 -wrap word 
    .top42.tex63 configure -font "TkTextFont"
    .top42.tex63 insert end text
    vTcl:DefineAlias "$top.tex63" "sitename_textbox" vTcl:WidgetProc "search_window" 1
    button $top.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Copy 
    vTcl:DefineAlias "$top.but64" "copy_sitename_btn" vTcl:WidgetProc "search_window" 1
    text $top.tex65 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 104 -wrap word 
    .top42.tex65 configure -font "TkTextFont"
    .top42.tex65 insert end text
    vTcl:DefineAlias "$top.tex65" "mapref_textbox" vTcl:WidgetProc "search_window" 1
    text $top.tex66 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 104 -wrap word 
    .top42.tex66 configure -font "TkTextFont"
    .top42.tex66 insert end text
    vTcl:DefineAlias "$top.tex66" "lat_textbox" vTcl:WidgetProc "search_window" 1
    button $top.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Copy 
    vTcl:DefineAlias "$top.but67" "copy_mapref_btn" vTcl:WidgetProc "search_window" 1
    button $top.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Copy 
    vTcl:DefineAlias "$top.but68" "copy_lat_btn" vTcl:WidgetProc "search_window" 1
    label $top.lab70 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Map Ref. :} 
    vTcl:DefineAlias "$top.lab70" "r_mapref_label" vTcl:WidgetProc "search_window" 1
    label $top.lab71 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Latitude :} 
    vTcl:DefineAlias "$top.lab71" "r_lat_label" vTcl:WidgetProc "search_window" 1
    label $top.lab72 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Longitude :} 
    vTcl:DefineAlias "$top.lab72" "r_long_label" vTcl:WidgetProc "search_window" 1
    text $top.tex73 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 104 -wrap word 
    .top42.tex73 configure -font "TkTextFont"
    .top42.tex73 insert end text
    vTcl:DefineAlias "$top.tex73" "long_textbox" vTcl:WidgetProc "search_window" 1
    button $top.but74 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Copy 
    vTcl:DefineAlias "$top.but74" "copy_long_btn" vTcl:WidgetProc "search_window" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.che43 \
        -in $top -x 30 -y 260 -anchor nw -bordermode ignore 
    place $top.tCo51 \
        -in $top -x 100 -y 160 -width 113 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 20 -y 100 -width 74 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 100 -y 40 -width 114 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 20 -y 70 -width 74 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 20 -y 40 -width 74 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 20 -y 10 -width 192 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent58 \
        -in $top -x 100 -y 70 -width 114 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent62 \
        -in $top -x 100 -y 100 -width 114 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent63 \
        -in $top -x 100 -y 130 -width 114 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent64 \
        -in $top -x 100 -y 220 -width 114 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent65 \
        -in $top -x 100 -y 190 -width 114 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 20 -y 130 -width 74 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 20 -y 190 -width 74 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 20 -y 220 -width 74 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 20 -y 160 -width 74 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but71 \
        -in $top -x 110 -y 260 -width 107 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr43 \
        -in $top -x 230 -y 40 -width 381 -relwidth 0 -height 245 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex45 \
        -in $top -x 690 -y 40 -width 104 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex46 \
        -in $top -x 690 -y 70 -width 104 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 620 -y 40 -width 64 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 620 -y 70 -width 60 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 810 -y 40 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 810 -y 70 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 350 -y 10 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 690 -y 10 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 620 -y 100 -width 60 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex60 \
        -in $top -x 690 -y 100 -width 104 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but61 \
        -in $top -x 810 -y 100 -width 39 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab62 \
        -in $top -x 620 -y 130 -width 60 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.tex63 \
        -in $top -x 690 -y 130 -width 104 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but64 \
        -in $top -x 810 -y 130 -width 39 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex65 \
        -in $top -x 690 -y 160 -width 104 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex66 \
        -in $top -x 690 -y 190 -width 104 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but67 \
        -in $top -x 810 -y 160 -width 39 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but68 \
        -in $top -x 810 -y 190 -width 39 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab70 \
        -in $top -x 620 -y 160 -width 60 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab71 \
        -in $top -x 620 -y 190 -width 60 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab72 \
        -in $top -x 620 -y 220 -width 60 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.tex73 \
        -in $top -x 690 -y 220 -width 104 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but74 \
        -in $top -x 810 -y 220 -width 39 -height 24 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

